name: Renew Docker Images

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]
on:
  schedule:
    - cron: "0 0 2 1 *"
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: pull velor2012/lookbusy-arm
        run: docker pull velor2012/lookbusy-arm
      - name: pull velor2012/lookbusy
        run: docker pull velor2012/lookbusy     
      - name: pull velor2012/robotimg
        run: docker pull velor2012/robotimg
